#!/usr/bin/env python3
import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell

# Read the existing notebook
with open('analyze_npz_structure.ipynb', 'r') as f:
    nb = nbformat.read(f, as_version=4)

# Find the Summary markdown cell index
summary_index = None
for i, cell in enumerate(nb.cells):
    if cell.cell_type == 'markdown' and '# Summary' in cell.source:
        summary_index = i
        break

if summary_index is None:
    print("Could not find Summary cell")
    exit(1)

print(f"Found Summary cell at index: {summary_index}")

# Create new cells as proper Cell objects
new_cells = []

# 1. Section header
new_cells.append(new_markdown_cell(
    "# AVI File Inference Section\n\n"
    "Direct inference from AVI video files with synchronized PPG ground truth comparison."
))

# 2. SCNN_9ROIs Model
new_cells.append(new_code_cell(
    "# ============================================================================\n"
    "# SCNN_9ROIs Model (Exact Architecture Matching Checkpoint)\n"
    "# ============================================================================\n"
    "\n"
    "class SCNN_9ROIs(nn.Module):\n"
    "    def __init__(self):\n"
    "        super(SCNN_9ROIs, self).__init__()\n"
    "        \n"
    "        # Matches checkpoint shapes: 27 input channels, 3x3x3 spatio-temporal kernels\n"
    "        self.spatial_temporal_feature_extractor = nn.Sequential(\n"
    "            nn.Conv3d(in_channels=27, out_channels=32, kernel_size=(3, 3, 3), padding=(1, 1, 1)),\n"
    "            nn.BatchNorm3d(32),\n"
    "            nn.ELU(),\n"
    "            nn.Conv3d(in_channels=32, out_channels=64, kernel_size=(3, 3, 3), padding=(1, 1, 1)),\n"
    "            nn.BatchNorm3d(64),\n"
    "            nn.ELU(),\n"
    "            nn.AdaptiveAvgPool3d((None, 1, 1))  # Collapses spatial (H, W) to 1x1, keeps temporal depth\n"
    "        )\n"
    "        \n"
    "        # Matches regression head weight shape: torch.Size([1, 64])\n"
    "        self.regression_head = nn.Linear(64, 1)\n"
    "\n"
    "    def forward(self, x):\n"
    "        # Expected input shape: [Batch, 27, Frames, H, W]\n"
    "        x = self.spatial_temporal_feature_extractor(x)  # Output shape: [Batch, 64, Frames, 1, 1]\n"
    "        \n"
    "        # Collapse spatial singleton dimensions -> [Batch, 64, Frames]\n"
    "        x = x.squeeze(-1).squeeze(-1)\n"
    "        \n"
    "        # Permute to frame-wise linear configuration -> [Batch, Frames, 64]\n"
    "        x = x.permute(0, 2, 1)\n"
    "        \n"
    "        # Apply the frame-wise regression head -> [Batch, Frames, 1]\n"
    "        out = self.regression_head(x)\n"
    "        \n"
    "        # Return standard flat layout -> [Batch, Frames]\n"
    "        return out.squeeze(-1)"
))

# 3. AVI Video Processing Configuration
new_cells.append(new_code_cell(
    "# ============================================================================\n"
    "# AVI Video Processing Configuration\n"
    "# ============================================================================\n"
    "\n"
    "# Configuration for video chunking\n"
    "CHUNK_SIZE = 450  # Number of frames per chunk\n"
    "OVERLAP_SIZE = 0  # No overlap for simplicity\n"
    "\n"
    "# ROI key mapping for AVI processing\n"
    "AVI_ROI_KEYS = ['forehead', 'left_eye', 'right_eye', 'nose', 'mouth', 'chin', \n"
    "               'right_cheek_50', 'left_cheek_280', 'chin_199']\n"
    "\n"
    "# Map AVI ROI keys to NPZ ROI keys\n"
    "AVI_TO_NPZ_ROI = {\n"
    "    'forehead': 'roi_forehead',\n"
    "    'left_eye': 'roi_left_eye',\n"
    "    'right_eye': 'roi_right_eye',\n"
    "    'nose': 'roi_nose',\n"
    "    'mouth': 'roi_mouth',\n"
    "    'chin': 'roi_chin',\n"
    "    'right_cheek_50': 'roi_right_cheek_50',\n"
    "    'left_cheek_280': 'roi_left_cheek_280',\n"
    "    'chin_199': 'roi_chin_199'\n"
    "}"
))

# 4. AVI Video Chunking
new_cells.append(new_code_cell(
    "# ============================================================================\n"
    "# AVI Video Chunking and Processing\n"
    "# ============================================================================\n"
    "\n"
    "def chunk_video_for_inference(video_path, chunk_size=CHUNK_SIZE, overlap_size=OVERLAP_SIZE):\n"
    "    \"\"\"Chunk video into manageable pieces for inference.\"\"\"\n"
    "    try:\n"
    "        import skvideo.io\n"
    "        videodata = skvideo.io.vread(video_path)\n"
    "        \n"
    "        if len(videodata) == 0:\n"
    "            return []\n"
    "        \n"
    "        # Split into chunks\n"
    "        chunks = []\n"
    "        for i in range(0, len(videodata), chunk_size - overlap_size):\n"
    "            end_idx = min(i + chunk_size, len(videodata))\n"
    "            chunk = videodata[i:end_idx]\n"
    "            \n"
    "            # Pad if necessary\n"
    "            if len(chunk) < chunk_size:\n"
    "                padding = chunk_size - len(chunk)\n"
    "                last_frame = chunk[-1:].repeat(padding, axis=0)\n"
    "                chunk = np.concatenate([chunk, last_frame], axis=0)\n"
    "            \n"
    "            chunks.append(chunk)\n"
    "        \n"
    "        return chunks\n"
    "    except Exception as e:\n"
    "        print(f\"Error chunking video: {e}\")\n"
    "        return []"
))

# 5. Process inference chunk
new_cells.append(new_code_cell(
    "def process_inference_chunk(chunk, detector, video_path=None):\n"
    "    \"\"\"Process a video chunk to extract ROIs for inference.\"\"\"\n"
    "    try:\n"
    "        import mediapipe as mp\n"
    "        \n"
    "        roi_data = {roi: [] for roi in AVI_ROI_KEYS}\n"
    "        all_landmarks = []\n"
    "        \n"
    "        for frame in chunk:\n"
    "            # Convert to RGB if needed\n"
    "            rgb_frame = frame.copy()\n"
    "            if len(rgb_frame.shape) == 2:\n"
    "                rgb_frame = np.stack([rgb_frame] * 3, axis=-1)\n"
    "            elif rgb_frame.shape[2] == 4:\n"
    "                rgb_frame = rgb_frame[:, :, :3]\n"
    "            \n"
    "            # Detect face landmarks\n"
    "            results = detector.process(rgb_frame)\n"
    "            \n"
    "            if results.multi_face_landmarks:\n"
    "                landmarks = results.multi_face_landmarks[0].landmark\n"
    "                height, width = frame.shape[:2]\n"
    "                landmark_points = np.array([\n"
    "                    (lmk.x * width, lmk.y * height) \n"
    "                    for lmk in landmarks\n"
    "                ])\n"
    "                all_landmarks.append(landmark_points)\n"
    "                \n"
    "                # Extract each ROI\n"
    "                for avi_roi_key in AVI_ROI_KEYS:\n"
    "                    npz_roi_key = AVI_TO_NPZ_ROI[avi_roi_key]\n"
    "                    if npz_roi_key in ROI_DEFINITIONS:\n"
    "                        roi_indices = ROI_DEFINITIONS[npz_roi_key]\n"
    "                        roi = extract_roi_from_frame(frame, landmark_points, roi_indices, size=24)\n"
    "                        if roi is not None:\n"
    "                            roi_data[avi_roi_key].append(roi)\n"
    "            else:\n"
    "                # No face detected - use previous landmarks\n"
    "                if all_landmarks:\n"
    "                    landmark_points = all_landmarks[-1]\n"
    "                    for avi_roi_key in AVI_ROI_KEYS:\n"
    "                        npz_roi_key = AVI_TO_NPZ_ROI[avi_roi_key]\n"
    "                        if npz_roi_key in ROI_DEFINITIONS:\n"
    "                            roi_indices = ROI_DEFINITIONS[npz_roi_key]\n"
    "                            roi = extract_roi_from_frame(frame, landmark_points, roi_indices, size=24)\n"
    "                            if roi is not None:\n"
    "                                roi_data[avi_roi_key].append(roi)\n"
    "        \n"
    "        # Stack ROIs into arrays\n"
    "        for key in roi_data:\n"
    "            if roi_data[key]:\n"
    "                roi_data[key] = np.stack(roi_data[key], axis=0)\n"
    "            else:\n"
    "                roi_data[key] = np.zeros((len(chunk), 24, 24, 3))\n"
    "        \n"
    "        return {'roi_data': roi_data, 'landmarks': all_landmarks}\n"
    "    except Exception as e:\n"
    "        print(f\"Error processing chunk: {e}\")\n"
    "        return None"
))

# 6. AVI File Inference with Ground Truth Comparison
new_cells.append(new_code_cell(
    "# ============================================================================\n"
    "# AVI File Inference with Ground Truth Comparison\n"
    "# ============================================================================\n"
    "\n"
    "def run_avi_inference(video_path, ppg_sync_path=None, model_path='best_scnn_9rois.pth'):\n"
    "    \"\"\"Run inference on AVI file with optional ground truth comparison.\"\"\"\n"
    "    \n"
    "    # Initialize device\n"
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
    "    print(f\"Target execution hardware: {device}\")\n"
    "    \n"
    "    # Initialize model\n"
    "    model = SCNN_9ROIs()\n"
    "    if os.path.exists(model_path):\n"
    "        model.load_state_dict(torch.load(model_path, map_location=device))\n"
    "        print(f\"Loaded model from {model_path}\")\n"
    "    else:\n"
    "        print(f\"Warning: Model not found at {model_path}. Using random weights.\")\n"
    "    \n"
    "    model.to(device)\n"
    "    model.eval()\n"
    "    \n"
    "    # Initialize MediaPipe detector\n"
    "    try:\n"
    "        import mediapipe as mp\n"
    "        detector = mp.solutions.face_mesh.FaceMesh(\n"
    "            static_image_mode=False,\n"
    "            max_num_faces=1,\n"
    "            refine_landmarks=True,\n"
    "            min_detection_confidence=0.5\n"
    "        )\n"
    "    except ImportError:\n"
    "        print(\"mediapipe not available. Install with: pip install mediapipe\")\n"
    "        return None\n"
    "    \n"
    "    # Chunk video\n"
    "    video_chunks = chunk_video_for_inference(video_path, chunk_size=CHUNK_SIZE, overlap_size=OVERLAP_SIZE)\n"
    "    if not video_chunks:\n"
    "        print(\"Video extraction yielded 0 active frames.\")\n"
    "        return None\n"
    "    \n"
    "    # Process first chunk\n"
    "    sample_chunk = video_chunks[0]\n"
    "    processed_data = process_inference_chunk(sample_chunk, detector, video_path=video_path)\n"
    "    \n"
    "    if processed_data is None:\n"
    "        print(\"Failed to process video chunk\")\n"
    "        return None\n"
    "    \n"
    "    roi_dict = processed_data['roi_data']\n"
    "    \n"
    "    # Extract and stack ROIs\n"
    "    rois_list = [roi_dict[key] for key in AVI_ROI_KEYS]\n"
    "    stacked_rois = np.concatenate(rois_list, axis=-1)  # (450, 24, 24, 27)\n"
    "    stacked_rois = np.transpose(stacked_rois, (3, 0, 1, 2))  # (27, 450, 24, 24)\n"
    "    \n"
    "    # Create tensor\n"
    "    input_tensor = torch.from_numpy(stacked_rois).float().unsqueeze(0)\n"
    "    if input_tensor.max() > 1.0:\n"
    "        input_tensor = input_tensor / 255.0\n"
    "    \n"
    "    input_tensor = input_tensor.to(device)\n"
    "    \n"
    "    # Run inference\n"
    "    with torch.no_grad():\n"
    "        predictions = model(input_tensor)\n"
    "    \n"
    "    pred_signal = predictions.squeeze(0).cpu().numpy()\n"
    "    print(f\"Predicted rPPG signal frame depth: {pred_signal.shape[0]} points.\")\n"
    "    \n"
    "    # Plot prediction\n"
    "    plt.figure(figsize=(15, 5))\n"
    "    timeline = np.arange(len(pred_signal)) / 30.0\n"
    "    plt.plot(timeline, pred_signal, label='SCNN Prediction', color='#e91e63', linewidth=2, linestyle='--')\n"
    "    plt.title(f\"AVI Video Inference: {Path(video_path).name}\", fontsize=12, fontweight='bold')\n"
    "    plt.xlabel('Timeline Duration (Seconds)')\n"
    "    plt.ylabel('Predicted PPG')\n"
    "    plt.legend(loc='upper right')\n"
    "    plt.grid(True, linestyle=':', alpha=0.5)\n"
    "    plt.tight_layout()\n"
    "    plt.show()\n"
    "    \n"
    "    # Compare with ground truth if available\n"
    "    if ppg_sync_path and os.path.exists(ppg_sync_path):\n"
    "        raw_gt = np.loadtxt(ppg_sync_path).astype(np.float32)\n"
    "        gt_signal = raw_gt[0:CHUNK_SIZE]\n"
    "        \n"
    "        if len(gt_signal) < len(pred_signal):\n"
    "            gt_signal = np.pad(gt_signal, (0, len(pred_signal) - len(gt_signal)), 'edge')\n"
    "        \n"
    "        # Standardize\n"
    "        pred_signal_norm = (pred_signal - np.mean(pred_signal)) / (np.std(pred_signal) + 1e-6)\n"
    "        gt_signal_norm = (gt_signal - np.mean(gt_signal)) / (np.std(gt_signal) + 1e-6)\n"
    "        \n"
    "        # Force to 1D and match lengths\n"
    "        pred_flat = pred_signal_norm.ravel()\n"
    "        gt_flat = gt_signal_norm.ravel()\n"
    "        min_len = min(len(pred_flat), len(gt_flat))\n"
    "        pred_flat = pred_flat[:min_len]\n"
    "        gt_flat = gt_flat[:min_len]\n"
    "        \n"
    "        # Plot comparison\n"
    "        plt.figure(figsize=(15, 5))\n"
    "        timeline = np.arange(min_len) / 30.0\n"
    "        plt.plot(timeline, gt_flat, label='Ground Truth BVP/PPG', color='#009688', linewidth=2)\n"
    "        plt.plot(timeline, pred_flat, label='SCNN Prediction', color='#e91e63', linewidth=2, linestyle='--')\n"
    "        plt.title(f\"SCNN 9-ROI Inference (Subject: {Path(video_path).stem})\", fontsize=12, fontweight='bold')\n"
    "        plt.xlabel('Timeline Duration (Seconds)')\n"
    "        plt.ylabel('Standardized Amplitude (Z-Score)')\n"
    "        plt.legend(loc='upper right')\n"
    "        plt.grid(True, linestyle=':', alpha=0.5)\n"
    "        plt.tight_layout()\n"
    "        plt.show()\n"
    "        \n"
    "        # Compute metrics\n"
    "        pearson_corr = np.corrcoef(pred_flat, gt_flat)[0, 1]\n"
    "        print(f\"Pearson Correlation (r): {pearson_corr:.4f}\")\n"
    "    else:\n"
    "        print(f\"[Note]: No PPG sync file provided or found at: {ppg_sync_path}\")\n"
    "    \n"
    "    return pred_signal"
))

# Insert new cells before the Summary
nb.cells = nb.cells[:summary_index] + new_cells + nb.cells[summary_index:]

# Save the updated notebook
with open('analyze_npz_structure.ipynb', 'w') as f:
    nbformat.write(nb, f)

print(f"Added {len(new_cells)} new cells before Summary")
print(f"Total cells now: {len(nb.cells)}")
